# Seed content for One Dot — REAL menu (from official menu image).
# Categories: Hot, Cold, Drip Coffee, Mojito. Editable via admin.

IMG = {
    "espresso": "https://images.unsplash.com/photo-1510707577719-ae7c14805e3a?auto=format&fit=crop&w=1200&q=80",
    "americano": "https://images.unsplash.com/photo-1521302080334-4bebac2763a6?auto=format&fit=crop&w=1200&q=80",
    "macchiato": "https://images.unsplash.com/photo-1485808191679-5f86510681a2?auto=format&fit=crop&w=1200&q=80",
    "cortado": "https://images.unsplash.com/photo-1559496417-e7f25cb247f3?auto=format&fit=crop&w=1200&q=80",
    "flatwhite": "https://images.unsplash.com/photo-1690609561635-f63c587b3aba?auto=format&fit=crop&w=1200&q=80",
    "cappuccino": "https://images.unsplash.com/photo-1497636577773-f1231844b336?auto=format&fit=crop&w=1200&q=80",
    "latte": "https://images.unsplash.com/photo-1561882468-9110e03e0f78?auto=format&fit=crop&w=1200&q=80",
    "spanish": "https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?auto=format&fit=crop&w=1600&q=85",
    "caramel": "https://images.unsplash.com/photo-1780285575743-e9008ef6c240?auto=format&fit=crop&w=1200&q=80",
    "whitemocha": "https://images.unsplash.com/photo-1475759697283-38cc56e4455a?auto=format&fit=crop&w=1200&q=80",
    "hotchoc": "https://images.unsplash.com/photo-1637572815755-c4b80092dce1?auto=format&fit=crop&w=1200&q=80",
    "iceamericano": "https://images.unsplash.com/photo-1517959105821-eaf2591984ca?auto=format&fit=crop&w=1200&q=80",
    "icespanish": "https://images.unsplash.com/photo-1642647391072-6a2416f048e5?auto=format&fit=crop&w=1200&q=80",
    "icewhitemocha": "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=1200&q=80",
    "icecaramel": "https://images.unsplash.com/photo-1687803799209-998b907f0ef4?auto=format&fit=crop&w=1200&q=80",
    "pistachio": "https://images.unsplash.com/photo-1770282184778-f474bd3a379a?auto=format&fit=crop&w=1600&q=85",
    "matcha": "https://images.pexels.com/photos/14704657/pexels-photo-14704657.jpeg?auto=compress&cs=tinysrgb&w=1600",
    "icechoc": "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=1200&q=80",
    "drip": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80",
    "chemex": "https://images.unsplash.com/photo-1519082274554-1ca37fb8abb7?auto=format&fit=crop&w=1200&q=80",
    "coffeeday": "https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=1200&q=80",
    "passion": "https://images.unsplash.com/photo-1648062876333-f414c92a4ba3?auto=format&fit=crop&w=1200&q=80",
    "berry": "https://images.unsplash.com/photo-1600332098294-2e6fefaa6d66?auto=format&fit=crop&w=1200&q=80",
    "roselle": "https://images.unsplash.com/photo-1549383343-ae4a50ca6281?auto=format&fit=crop&w=1200&q=80",
    "peach": "https://images.unsplash.com/photo-1587437430404-61c2024738b6?auto=format&fit=crop&w=1200&q=80",
}


def item(**kw):
    base = dict(name_ar="", desc_en="", desc_ar="", ingredients_en="", ingredients_ar="",
               calories="", price=0, category="Hot", image="", options=[], addons=[],
               is_signature=False, signature_no="", order=0, available=True)
    base.update(kw)
    return base


MILK = [
    {"label_en": "Regular Milk", "label_ar": "حليب عادي", "price_delta": 0},
    {"label_en": "Oat Milk", "label_ar": "حليب الشوفان", "price_delta": 3},
    {"label_en": "Almond Milk", "label_ar": "حليب اللوز", "price_delta": 3},
]
ADD = [
    {"label_en": "Extra Shot", "label_ar": "جرعة إضافية", "price_delta": 4},
    {"label_en": "Vanilla Syrup", "label_ar": "سيرب فانيلا", "price_delta": 3},
    {"label_en": "Caramel Syrup", "label_ar": "سيرب كراميل", "price_delta": 3},
]

MENU_ITEMS = [
    # ---------------- HOT ساخنة ----------------
    item(name_en="Espresso", name_ar="اسبريسو", category="Hot", price=10, calories="3", image=IMG["espresso"], order=1,
         desc_en="A pure, concentrated shot — the heart of every cup.",
         desc_ar="جرعة نقية ومركّزة — قلب كل فنجان.",
         ingredients_en="Single origin espresso", ingredients_ar="إسبريسو أحادي المصدر", addons=ADD),
    item(name_en="Americano", name_ar="امريكانو", category="Hot", price=12, calories="5", image=IMG["americano"], order=2,
         desc_en="Espresso opened up with hot water. Clean and bold.",
         desc_ar="إسبريسو مع ماء ساخن. نقي وغني.",
         ingredients_en="Espresso, hot water", ingredients_ar="إسبريسو، ماء ساخن", addons=ADD),
    item(name_en="Macchiato", name_ar="ماكياتو", category="Hot", price=12, calories="47", image=IMG["macchiato"], order=3,
         desc_en="Espresso marked with a touch of foamed milk.",
         desc_ar="إسبريسو مع لمسة من رغوة الحليب.",
         ingredients_en="Espresso, milk foam", ingredients_ar="إسبريسو، رغوة حليب", options=MILK, addons=ADD),
    item(name_en="Cortado", name_ar="كورتادو", category="Hot", price=13, calories="65", image=IMG["cortado"], order=4,
         desc_en="Equal parts espresso and warm milk. Perfectly balanced.",
         desc_ar="إسبريسو وحليب دافئ بنسب متساوية. متوازن تماماً.",
         ingredients_en="Espresso, steamed milk", ingredients_ar="إسبريسو، حليب مبخّر", options=MILK, addons=ADD),
    item(name_en="Flat White", name_ar="فلات وايت", category="Hot", price=14, calories="71", image=IMG["flatwhite"], order=5,
         desc_en="Silky microfoam over a double ristretto.",
         desc_ar="رغوة حريرية فوق ريستريتو مزدوج.",
         ingredients_en="Double ristretto, microfoam", ingredients_ar="ريستريتو مزدوج، رغوة دقيقة", options=MILK, addons=ADD),
    item(name_en="Cappuccino", name_ar="كابتشينو", category="Hot", price=15, calories="79", image=IMG["cappuccino"], order=6,
         desc_en="Classic balance of espresso, milk and velvet foam.",
         desc_ar="توازن كلاسيكي من الإسبريسو والحليب والرغوة.",
         ingredients_en="Espresso, steamed milk, foam", ingredients_ar="إسبريسو، حليب مبخّر، رغوة", options=MILK, addons=ADD),
    item(name_en="Latte", name_ar="لاتيه", category="Hot", price=16, calories="136", image=IMG["latte"], order=7,
         desc_en="Smooth espresso with steamed milk and a thin layer of foam.",
         desc_ar="إسبريسو ناعم مع حليب مبخّر وطبقة رغوة رقيقة.",
         ingredients_en="Espresso, steamed milk", ingredients_ar="إسبريسو، حليب مبخّر", options=MILK, addons=ADD),
    item(name_en="Spanish Latte", name_ar="سبانيش لاتيه", category="Hot", price=18, calories="217", image=IMG["spanish"], order=8,
         is_signature=True, signature_no="01",
         desc_en="Sweet condensed milk meets bold espresso — our house favorite.",
         desc_ar="حليب مكثّف محلّى مع إسبريسو غني — الأكثر طلباً لدينا.",
         ingredients_en="Espresso, condensed milk, steamed milk", ingredients_ar="إسبريسو، حليب مكثّف، حليب مبخّر", options=MILK, addons=ADD),
    item(name_en="Caramel Latte", name_ar="كراميل لاتيه", category="Hot", price=18, calories="230", image=IMG["caramel"], order=9,
         desc_en="Latte swirled with buttery caramel.",
         desc_ar="لاتيه ممزوج بالكراميل الغني.",
         ingredients_en="Espresso, milk, caramel", ingredients_ar="إسبريسو، حليب، كراميل", options=MILK, addons=ADD),
    item(name_en="White Mocha", name_ar="وايت موكا", category="Hot", price=18, calories="190", image=IMG["whitemocha"], order=10,
         desc_en="Espresso and steamed milk with smooth white chocolate.",
         desc_ar="إسبريسو وحليب مبخّر مع شوكولاتة بيضاء ناعمة.",
         ingredients_en="Espresso, milk, white chocolate", ingredients_ar="إسبريسو، حليب، شوكولاتة بيضاء", options=MILK, addons=ADD),
    item(name_en="Hot Chocolate", name_ar="شوكولاته ساخنه", category="Hot", price=20, calories="104", image=IMG["hotchoc"], order=11,
         desc_en="Rich melted chocolate and steamed milk.",
         desc_ar="شوكولاتة ذائبة غنية وحليب مبخّر.",
         ingredients_en="Chocolate, milk", ingredients_ar="شوكولاتة، حليب", options=MILK),

    # ---------------- COLD باردة ----------------
    item(name_en="Ice Americano", name_ar="ايس امريكانو", category="Cold", price=12, calories="5", image=IMG["iceamericano"], order=20,
         desc_en="Espresso over ice and cold water. Crisp and refreshing.",
         desc_ar="إسبريسو مع ثلج وماء بارد. منعش ونقي.",
         ingredients_en="Espresso, water, ice", ingredients_ar="إسبريسو، ماء، ثلج", addons=ADD),
    item(name_en="Ice Spanish Latte", name_ar="ايس سبانيش لاتيه", category="Cold", price=18, calories="217", image=IMG["icespanish"], order=21,
         desc_en="Our signature Spanish latte, served over ice.",
         desc_ar="السبانيش لاتيه المميز مقدّم مع الثلج.",
         ingredients_en="Espresso, condensed milk, milk, ice", ingredients_ar="إسبريسو، حليب مكثّف، حليب، ثلج", options=MILK, addons=ADD),
    item(name_en="Ice White Mocha", name_ar="ايس وايت موكا", category="Cold", price=18, calories="190", image=IMG["icewhitemocha"], order=22,
         desc_en="Iced white chocolate mocha, smooth and sweet.",
         desc_ar="وايت موكا مثلّجة، ناعمة وحلوة.",
         ingredients_en="Espresso, milk, white chocolate, ice", ingredients_ar="إسبريسو، حليب، شوكولاتة بيضاء، ثلج", options=MILK, addons=ADD),
    item(name_en="Ice Caramel Latte", name_ar="ايس كراميل لاتيه", category="Cold", price=18, calories="230", image=IMG["icecaramel"], order=23,
         desc_en="Chilled caramel latte over ice.",
         desc_ar="كراميل لاتيه بارد مع الثلج.",
         ingredients_en="Espresso, milk, caramel, ice", ingredients_ar="إسبريسو، حليب، كراميل، ثلج", options=MILK, addons=ADD),
    item(name_en="Ice Pistachio", name_ar="ايس بستاشيو", category="Cold", price=18, calories="485", image=IMG["pistachio"], order=24,
         is_signature=True, signature_no="02",
         desc_en="Creamy iced pistachio latte with a nutty finish.",
         desc_ar="لاتيه بستاشيو مثلّج كريمي بنكهة مكسّرات غنية.",
         ingredients_en="Espresso, milk, pistachio, ice", ingredients_ar="إسبريسو، حليب، فستق، ثلج", options=MILK, addons=ADD),
    item(name_en="Ice Matcha Latte", name_ar="ايس ماتشا لاتيه", category="Cold", price=19, calories="277", image=IMG["matcha"], order=25,
         is_signature=True, signature_no="03",
         desc_en="Ceremonial grade matcha whisked with cold milk over ice.",
         desc_ar="ماتشا درجة احتفالية مخفوقة مع حليب بارد وثلج.",
         ingredients_en="Ceremonial matcha, milk, ice", ingredients_ar="ماتشا احتفالية، حليب، ثلج", options=MILK, addons=ADD),
    item(name_en="Ice Chocolate", name_ar="ايس تشوكلت", category="Cold", price=16, calories="104", image=IMG["icechoc"], order=26,
         desc_en="Chilled chocolate with milk over ice.",
         desc_ar="شوكولاتة باردة مع حليب وثلج.",
         ingredients_en="Chocolate, milk, ice", ingredients_ar="شوكولاتة، حليب، ثلج", options=MILK),

    # ---------------- DRIP COFFEE القهوة المقطّرة ----------------
    item(name_en="V60", name_ar="في 60", category="Drip Coffee", price=18, calories="3", image=IMG["drip"], order=30,
         desc_en="Hand-poured pour-over highlighting bright, delicate notes.",
         desc_ar="تحضير يدوي بالتقطير يُبرز النكهات الرقيقة.",
         ingredients_en="Single origin filter coffee", ingredients_ar="قهوة فلتر أحادية المصدر"),
    item(name_en="Chemex", name_ar="كيمكس", category="Drip Coffee", price=18, calories="2", image=IMG["chemex"], order=31,
         desc_en="Clean, smooth filter brew with a silky body.",
         desc_ar="تقطير نقي وناعم بقوام حريري.",
         ingredients_en="Single origin filter coffee", ingredients_ar="قهوة فلتر أحادية المصدر"),
    item(name_en="Coffee Of The Day (Small)", name_ar="قهوه اليوم صغير", category="Drip Coffee", price=8, calories="3", image=IMG["coffeeday"], order=32,
         desc_en="Today's rotating filter selection.",
         desc_ar="اختيار الفلتر المتغيّر لهذا اليوم.",
         ingredients_en="Filter coffee", ingredients_ar="قهوة فلتر"),
    item(name_en="Coffee Of The Day (Large)", name_ar="قهوه اليوم كبير", category="Drip Coffee", price=10, calories="3", image=IMG["coffeeday"], order=33,
         desc_en="Today's rotating filter selection — larger serve.",
         desc_ar="اختيار الفلتر المتغيّر لهذا اليوم — بحجم أكبر.",
         ingredients_en="Filter coffee", ingredients_ar="قهوة فلتر"),

    # ---------------- MOJITO موهيتو ----------------
    item(name_en="Mojito Passion Fruit", name_ar="موهيتو باشن فروت", category="Mojito", price=15, calories="179", image=IMG["passion"], order=40,
         desc_en="Sparkling passion fruit with mint. Bright and refreshing.",
         desc_ar="باشن فروت فوّار مع النعناع. منعش ونضر.",
         ingredients_en="Passion fruit, mint, soda, ice", ingredients_ar="باشن فروت، نعناع، صودا، ثلج"),
    item(name_en="Mix Berry Mojito", name_ar="موهيتو مكس بيري", category="Mojito", price=15, calories="201", image=IMG["berry"], order=41,
         desc_en="Mixed berries, mint and soda over ice.",
         desc_ar="توت مشكّل مع نعناع وصودا وثلج.",
         ingredients_en="Mixed berries, mint, soda, ice", ingredients_ar="توت مشكّل، نعناع، صودا، ثلج"),
    item(name_en="Roselle", name_ar="كركديه", category="Mojito", price=12, calories="104", image=IMG["roselle"], order=42,
         desc_en="Chilled hibiscus infusion — tart and floral.",
         desc_ar="نقيع كركديه بارد — حامض وعطري.",
         ingredients_en="Hibiscus, ice", ingredients_ar="كركديه، ثلج"),
    item(name_en="Peach Iced Tea", name_ar="ايس تي خوخ", category="Mojito", price=14, calories="339", image=IMG["peach"], order=43,
         desc_en="House-brewed iced tea with sweet peach.",
         desc_ar="شاي مثلّج محضّر لدينا بنكهة الخوخ الحلو.",
         ingredients_en="Black tea, peach, ice", ingredients_ar="شاي أسود، خوخ، ثلج"),
]

SETTINGS = {
    "rating": 4.5,
    "reviews_count": 210,
    "price_min": 20,
    "price_max": 40,
    "address_en": "Mecca 24226, Saudi Arabia",
    "address_ar": "مكة المكرمة، 24226",
    "plus_code": "FQ27+22",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=FQ27%2B22+Mecca",
    "directions_url": "https://www.google.com/maps/dir/?api=1&destination=FQ27%2B22+Mecca",
    "whatsapp": "",
    "instagram": "",
    "hours_weekday_en": "Sat – Thu · 6:30 AM — 2:30 AM",
    "hours_weekday_ar": "السبت – الخميس · 6:30 ص — 2:30 ص",
    "hours_friday_en": "Friday · 4:30 PM — 3:00 AM",
    "hours_friday_ar": "الجمعة · 4:30 م — 3:00 ص",
    "gallery": [
        "https://customer-assets-cm19k8pv.emergentagent.net/job_find-your-dot/artifacts/1g3n9q0t_WhatsApp%20Image%202026-08-12%20at%202.57.56%20PM%20%281%29.jpeg",
        "https://customer-assets-cm19k8pv.emergentagent.net/job_find-your-dot/artifacts/wyqowqza_WhatsApp%20Image%202026-08-12%20at%202.57.57%20PM.jpeg",
        "https://customer-assets-cm19k8pv.emergentagent.net/job_find-your-dot/artifacts/e5kqz31q_WhatsApp%20Image%202026-08-12%20at%202.57.57%20PM%20%281%29.jpeg",
        "https://customer-assets-cm19k8pv.emergentagent.net/job_find-your-dot/artifacts/1jqwwpdq_WhatsApp%20Image%202026-08-12%20at%202.57.56%20PM.jpeg",
    ],
    "instagram_grid": [
        "https://customer-assets-cm19k8pv.emergentagent.net/job_find-your-dot/artifacts/wyqowqza_WhatsApp%20Image%202026-08-12%20at%202.57.57%20PM.jpeg",
        "https://customer-assets-cm19k8pv.emergentagent.net/job_find-your-dot/artifacts/e5kqz31q_WhatsApp%20Image%202026-08-12%20at%202.57.57%20PM%20%281%29.jpeg",
        "https://customer-assets-cm19k8pv.emergentagent.net/job_find-your-dot/artifacts/1jqwwpdq_WhatsApp%20Image%202026-08-12%20at%202.57.56%20PM.jpeg",
        "https://customer-assets-cm19k8pv.emergentagent.net/job_find-your-dot/artifacts/1g3n9q0t_WhatsApp%20Image%202026-08-12%20at%202.57.56%20PM%20%281%29.jpeg",
        "https://images.unsplash.com/photo-1497636577773-f1231844b336?auto=format&fit=crop&w=600&q=80",
        "https://images.unsplash.com/photo-1770282184778-f474bd3a379a?auto=format&fit=crop&w=600&q=80",
        "https://images.pexels.com/photos/14704657/pexels-photo-14704657.jpeg?auto=compress&cs=tinysrgb&w=600",
        "https://images.unsplash.com/photo-1642647391072-6a2416f048e5?auto=format&fit=crop&w=600&q=80",
        "https://images.unsplash.com/photo-1549383343-ae4a50ca6281?auto=format&fit=crop&w=600&q=80",
    ],
    "reviews": [
        {"name_en": "Layla A.", "name_ar": "ليلى ع.", "rating": 5,
         "text_en": "The Spanish Latte is unlike anything in Mecca. Every detail feels intentional.",
         "text_ar": "السبانيش لاتيه لا يشبه أي شيء في مكة. كل تفصيل مدروس."},
        {"name_en": "Omar K.", "name_ar": "عمر ك.", "rating": 4.5,
         "text_en": "Cozy, cinematic space and genuinely excellent espresso. My new spot.",
         "text_ar": "مكان دافئ وأنيق وإسبريسو ممتاز فعلاً. مكاني المفضّل الجديد."},
        {"name_en": "Sara M.", "name_ar": "سارة م.", "rating": 4.5,
         "text_en": "The Ice Pistachio and V60 are worth the visit alone. Beautiful service.",
         "text_ar": "الآيس بستاشيو والـV60 يستحقان الزيارة وحدهما. خدمة راقية."},
    ],
}
